#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: preprocess

target:
  name: itpeastusv100cl
  #name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/


jobs:  
- name: binary_en-id
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh en id
- name: binary_en-jv
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh en jv
- name: binary_en-ms
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh en ms
- name: binary_en-ta
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh en ta
- name: binary_en-tl
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh en tl
- name: binary_id-jv
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh id jv
- name: binary_id-ms
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh id ms
- name: binary_id-ta
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh id ta
- name: binary_id-tl
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh id tl
- name: binary_jv-ms
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh jv ms
- name: binary_jv-ta
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh jv ta
- name: binary_jv-tl
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh jv tl
- name: binary_ms-ta
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh ms ta
- name: binary_ms-tl
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh ms tl
- name: binary_ta-tl
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/small_track2/thunder/binary_lang_pair.sh ta tl




