#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  #name: itplabrr1cl1
  service: amlk8s
  #vc: resrchvc
  #name: itpwus2v100cl
  #service: amlk8s
  #vc: gcrprojvc1
  #vc: resrchvc
  #name: v100-8x-eus-1
  #vc: quantus
  #name: v100-8x-scus
  #service: amlk8s
  #vc: quantus
  name: itplabrr1cl1
  vc: resrchvc

environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  #- python -m pip install pyarrow --user
  #- python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/


jobs:
- name: train_from_deltalm_postnorm_small_track1
  sku: G8
  sku_count: 1
  command:
    - bash ./shells/aml/multi-node/small_task1/Filter_v1/8GPU/V100/FT_24L_12L.sh