#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  name: itpeastusv100cl
  #name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  #- python -m pip install pyarrow --user
  #- python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

#data:
#  data_upload: False
#  local_dir: /home/v-jiaya/DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/
#  remote_dir: DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/

jobs:  
- name: small_task1_parallel_bt_split_v1_en
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train/train.en -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-split10/ -split-num 10
- name: small_task1_parallel_bt_split_v1_et
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train/train.et -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-split10/ -split-num 10
- name: small_task1_parallel_bt_split_v1_hr
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train/train.hr -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-split10/ -split-num 10
- name: small_task1_parallel_bt_split_v1_hu
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train/train.hu -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-split10/ -split-num 10
- name: small_task1_parallel_bt_split_v1_mk
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train/train.mk -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-split10/ -split-num 10
- name: small_task1_parallel_bt_split_v1_sr
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train/train.sr -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-split10/ -split-num 10