#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  #name: itpeastusv100cl
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/


jobs:  
- name: filter_en-et
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track1/filter_e2x_bt.sh en et 
- name: filter_en-hr
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track1/filter_e2x_bt.sh en hr 
- name: filter_en-hu
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track1/filter_e2x_bt.sh en hu 
- name: filter_en-mk
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track1/filter_e2x_bt.sh en mk 
- name: filter_en-sr
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track1/filter_e2x_bt.sh en sr 



