#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  #name: itpeastusv100cl
  name: itplabrr1cl1
  service: amlk8s
  vc: resrchvc


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  #- python -m pip install pyarrow --user
  #- python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

#data:
#  data_upload: False
#  local_dir: /home/v-jiaya/DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/
#  remote_dir: DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/

jobs:  
- name: en.tsv.filt001-en2gl
  sku: G1
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/translate.sh en gl 2 /mnt/input/SharedTask/large-scale/PretrainedModel/mm100_615M/flores101_mm100_615M/model.pt en.tsv.filt001 en001.2gl 64
- name: en.tsv.filt001-en2ko
  sku: G1
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/translate.sh en ko 2 /mnt/input/SharedTask/large-scale/PretrainedModel/mm100_615M/flores101_mm100_615M/model.pt en.tsv.filt001 en001.2ko 64
- name: en.tsv.filt001-en2hy
  sku: G1
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/translate.sh en hy 2 /mnt/input/SharedTask/large-scale/PretrainedModel/mm100_615M/flores101_mm100_615M/model.pt en.tsv.filt001 en001.2hy 64
- name: en.tsv.filt001-en2hu
  sku: G1
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/translate.sh en hu 2 /mnt/input/SharedTask/large-scale/PretrainedModel/mm100_615M/flores101_mm100_615M/model.pt en.tsv.filt001 en001.2hu 64
