#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  service: amlk8s
  #name: itplabrr1cl1
  #name: itpeastusv100cl
  #name: itplabrl1cl1
  #vc: resrchvc
  #name: a100-scus
  #service: amlk8s
  #vc: language-itp-mt-res
  name: itp-p40-wus2
  vc: language-itp-mtres
  #name: itpwus2cpucl1
  #vc: gcrcpu


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  #- python -m pip install pyarrow --user
  #- python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

#data:
#  data_upload: False
#  local_dir: /home/v-jiaya/DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/
#  remote_dir: DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/

jobs:  
- name: concat_x2y_bt_id
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track2/concat_x2y_bt.sh id
- name: concat_x2y_bt_jv
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track2/concat_x2y_bt.sh jv
- name: concat_x2y_bt_ms
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track2/concat_x2y_bt.sh ms
- name: concat_x2y_bt_ta
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track2/concat_x2y_bt.sh ta
- name: concat_x2y_bt_tl
  sku: G0
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/small_track2/concat_x2y_bt.sh tl
