#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  service: amlk8s
  #name: itplabrr1cl1
  #name: itpeastusv100cl
  #name: itplabrl1cl1
  #vc: resrchvc
  #name: a100-scus
  #service: amlk8s
  #vc: language-itp-mt
  #name: itpwus2cpucl1
  #vc: gcrcpu
  name: itp-p40-wus2
  vc: language-itp-mtres


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - pip install xlwt
  - pip install xlrd
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

#data:
#  data_upload: False
#  local_dir: /home/v-jiaya/DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/
#  remote_dir: DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/

jobs:  
#- name: generate_pivot_pairs_large_track_24L_6L
#  sku: G0
#  sku_count: 1
#  command: 
#    - python ./scripts/SharedTask/large_track/generate_pivot_pair_large_track.py -checkpoint-name /mnt/input/SharedTask/thunder/large_track/data/model/deltalm/FULL-v1/lr1e-4-deltalm-postnorm-24L-6L/avg30_39.pt -threshold 0 -pivot-pairs /mnt/input/SharedTask/thunder/flores101_dataset/pivot_pairs_24L_6L.txt

#- name: generate_pivot_pairs_large_track_24L_12L
#  sku: G0
#  sku_count: 1
#  command: 
#    - python ./scripts/SharedTask/large_track/generate_pivot_pair_large_track.py -checkpoint-name /mnt/input/SharedTask/thunder/large_track/data/Filter_v1/model/24L-12L/avg61_80.pt -threshold 0 -pivot-pairs /mnt/input/SharedTask/thunder/flores101_dataset/pivot_pairs_24L_12L.txt
    
- name: generate_pivot_pairs_large_track_36L_12L1
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/large_track/generate_pivot_pair_large_track.py -checkpoint-name /mnt/input/SharedTask/thunder/large_track/data/Filter_v1/model/36L-12L/avg26_40.pt -threshold 0 -pivot-pairs /mnt/input/SharedTask/thunder/flores101_dataset/pivot_pairs_36L_12L.txt

- name: generate_pivot_pairs_large_track_36L_12L2
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/large_track/generate_pivot_pair_large_track.py -checkpoint-name /mnt/input/SharedTask/thunder/large_track/data/Filter_v1/model/36L-12L/avg26_45.pt -threshold 0 -pivot-pairs /mnt/input/SharedTask/thunder/flores101_dataset/pivot_pairs_36L_12L.txt