#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: xlm-t

target:
  name: v100-8x-eus-1
  service: dlts
  vc: quantus

environment:
  image: nvidia/20.09:v1
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  - python -m pip install pyarrow --user
  - python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

data:
  data_upload: False
  local_dir: /home/v-jiaya/DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/
  remote_dir: DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/

jobs:  
- name: xlmt_swapadapter_step1.sh
  sku: G8
  sku_count: 2
  aml_mpirun:
    communicator: OpenMpi
  command:
   - bash ./shells/aml/multi-node/sparse/xlmt_swapadapter_step1.sh