#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask
target:
  service: amlk8s
  #name: itpeastusv100cl
  #name: itplabrr1cl1
  #vc: resrchvc
  name: v100-8x-scus
  vc: quantus


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  #- python -m pip install pyarrow --user
  #- python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

#data:
#  data_upload: False
#  local_dir: /home/v-jiaya/DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/
#  remote_dir: DeepTransformerModel/data/iwslt17/mTED/data-bin-fp16/

jobs:  
- name: zh2en_translation
  sku: G1
  sku_count: 1
  command: 
    - bash ./shells/preprocess/BT/large_track/translate.sh zh en 5 /mnt/input/SharedTask/thunder/large_track/data/Filter_v1/model/24L-12L/checkpoint59.pt zh.txt0000 zh0000.2en 64

