#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: preprocess

target:
  name: itpeastusv100cl
  #name: itplabrr1cl1
  #service: amlk8s
  #vc: resrchvc
  name: itp-p40-wus2
  vc: language-itp-mtres


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/


jobs:  
- name: small_task1_filter_parallel_bt1.5
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/small_track1/filter_parallel_bt.py -input /mnt/input/SharedTask/thunder/MonolingualData/all_spm_x2e_bt/ -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train1.5/ -length-ratio 1.5
- name: small_task1_filter_parallel_bt2.0
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/small_track1/filter_parallel_bt.py -input /mnt/input/SharedTask/thunder/MonolingualData/all_spm_x2e_bt/ -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.0/ -length-ratio 2.0
- name: small_task1_filter_parallel_bt2.5
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/small_track1/filter_parallel_bt.py -input /mnt/input/SharedTask/thunder/MonolingualData/all_spm_x2e_bt/ -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/ -length-ratio 2.5
