#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: SharedTask

target:
  service: amlk8s
  #name: itpeastusv100cl
  #name: itplabrr1cl1
  #vc: resrchvc
  name: itpwus2cpucl1     
  vc: gcrcpu


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 4096
  - python -m pip install --editable . --user
  #- python -m pip install pyarrow --user
  #- python -m pip install fairscale --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

jobs: 
- name: small_task1_parallel_bt2.5_split_v1_en
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/train.en -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt2.5-split10/ -split-num 10
- name: small_task1_parallel_bt2.5_split_v1_et
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/train.et -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt2.5-split10/ -split-num 10
- name: small_task1_parallel_bt2.5_split_v1_hr
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/train.hr -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt2.5-split10/ -split-num 10
- name: small_task1_parallel_bt2.5_split_v1_hu
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/train.hu -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt2.5-split10/ -split-num 10
- name: small_task1_parallel_bt2.5_split_v1_mk
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/train.mk -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt2.5-split10/ -split-num 10
- name: small_task1_parallel_bt2.5_split_v1_sr
  sku: G0
  sku_count: 1
  command: 
    - python ./scripts/SharedTask/SplitTrainingData.py -input /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt-train2.5/train.sr -output /mnt/input/SharedTask/thunder/small_task1/Filter_v1/parallel_bt2.5-split10/ -split-num 10


