#docker's key: /r9XLj/sS40pDvIvzamSeWZHApMhEc1r
description: DebugTrain

target:
  #name: itplabrr1cl1
  #name: itpeastusv100cl
  #service: amlk8s
  #vc: resrchvc
  
  name: v100-32gb-eus-2
  service: amlk8s
  vc: language-itp-mtres


environment:
  image: nvidia/20.09:v7.0.2
  registry: shumingdocker.azurecr.io
  setup:
  - ibstat
  - ulimit -n 40960
  - python -m pip install --editable . --user
  username: shumingdocker
  
storage:
  output:
    storage_account_name: yangjianblob
    container_name: phillytools
  input:
    storage_account_name: yangjianblob
    container_name: phillytools

code:
  # local directory of the code. this will be uploaded to the server.
  # $CONFIG_DIR is expanded to the directory of this config file
  local_dir: $CONFIG_DIR/

jobs:  
- name: debug
  sku: G1
  sku_count: 1
  command: 
    - bash ./shells/aml/multi-node/large_task1/deltalm/1GPU/train.sh



